export const aboutDept = [
  "The Department of Electronic and Communication Engineering (ECE), National Institute of Technology Delhi was established in 2010, immediately with the beginning of the Institute under the aegis of the Ministry of Human Resource and Development (MHRD), Govt. of India.",
  "Currently, it is offering one Undergraduate (B. Tech.) Program and two Postgraduate (M. Tech) programs in ECE and VLSI Design. The Department also offers Ph.D. and Post-Doctoral Fellowship (PDF) Programme in relevant areas, like electronic devices and circuits, semiconductor photonics, optical communication and opto-electronics, signal & speech processing, analog & digital VLSI design and circuits, antenna & wave propagation, networking, AI and ML etc.",
  "It has excellent laboratories and research facilities in electronic devices and circuits, electronic measurement and instrumentation, microprocessor and microcontroller, microwave and antenna design, optical fiber communication and optical device, multimedia, and advanced communication and design automation and simulation laboratory. The faculty of the department has published 123 reputed international journal papers and 78 international/ national conference papers in the last 3 academic years. Departmental faculty has published journal papers in IEEE Transaction on Electronic devices, IEEE Photonics Technology, IEEE Electron Devices, Springer journals, Elsevier journals etc. The Department and faculty members have received projects, grants, and fellowships from the Ministry of Electronics and Information Technology (MeitY), the Department of Science and Technology (DST)-SERB, and other funding agencies. The Department has active collaborations with academic Institutes & research institutes in India and abroad.",
  "The Department of ECE has a blend of young as well as experienced dynamic faculty members and is committed to providing quality education and research in the field. Faculty members of the department have excellent academic & research credentials and published numerous articles in the diversified field and have adequate experience in advanced research. The department of ECE provides a creative learning environment to the students for excellence in technical education. The department hopes to achieve the national goals and objectives of industrialization and self-reliance.",
];

export const aboutConf = [
  "First International Conference on Electronics, Communication and Signal Processing (ICECSP 2024) provides a platform for researchers, academics, scholars, industry experts from India and the world to present and discuss their research findings in various areas of Electronics and Communication Engineering. However, ICECSP 2024 solicits original papers’ contributions in all related areas of Electronics Engineering. ICECSP 2024 is organized by Dept. of Electronics and communication Engineering, National Institute of Technology, Delhi during August 8-10 (Thursday – Saturday), 2024.",
  "The major tracks of the conference are focused on Microelectronic Circuits and Systems, Communication Systems & Networks, Signal Processing & Applications, and VLSI Technology & Embedded Systems. The conference will feature keynote speakers, technical sessions, and workshops covering a wide range of topics related to Microelectronics, VLSI Design, Signal Processing and Communication systems.",
  "The conference is technically supported by IEEE Delhi section (record number#61809)"
];
